[project]
name = "3-agent-with-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TulasiRam K", email = "tulasiram.k.ai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.2.9",
    "streamlit>=1.40.0",
    "pytest>=8.0.0",
]

[project.scripts]
3-agent-with-tool = "3_agent_with_tool:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
